name = "SGU Packet"
author = "jasonxue"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c4a21bfe12f313bb4393375020a1dd7fbd8d07f9c73ec7051c84ab4c642130d"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1", "26.1.2"]
