name = "SGU Packet"
author = "jasonxue"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "304536fac2a1904123df17ecf6f9928e2736a953e49ea73464fd0b4e4070d61c"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1", "26.1.2"]
